name: gip-vibe
channels:
  - pytorch
  - anaconda
  - conda-forge
  - numba
dependencies:
  - python=3.7            # python!!!
  - numpy=1.17            # linear algebra
  - pytorch=1.4           # deep learning framework
  - torchvision=0.5       # deep learning for computer vision
  - tqdm=4.28             # progress bar
  - scipy=1.4             # scientific computing
  - numba=0.47            # python static compiler
  - gdown=3.*             # for downloading from google drive
  - joblib=0.14           # parallel processing
  - trimesh=3.5           # geometric processing of meshes
  - progress=1.5          # progress bar
  - filterpy=1.4          # implementation of bayesian filters
  - matplotlib=3.1        # visualizations
  - scikit-image=0.16     # image processing algorithms
  - scikit-video=1.1      # video processing algorithms
  - pillow=6.2            # image reading/writing
  - opencv=4.1            # computer vision
  - git                   # git:)

## other packages installed with pip:
  # smplx - for the body shape parameters
  # pyrender - to render the images
  # pytube - to download from youtube
  # git+https://github.com/mattloper/chumpy.git - to use auto grad? why is it a dependency?
  # git+https://github.com/mkocabas/yolov3-pytorch.git - YOLOv3 implementation for tracking humans
  # git+https://github.com/mkocabas/multi-person-tracker.git - ^^^ multi person tracking
# TODO: figure out what dependencies here are redundant, and remove them
